### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by LeoColomb** [slapperwan/gh4a#178]
Thanks a lot for all previous issues I file and you have fixed. Hope it's useful.
This is the last big issue I found, before OctoDroid expect perfection. :smile: 
- [x] Comments Icon on Issue List (#183)
- [x] Repository numbers (#183 - #185)
- [x] Theming (and improve) code view (#186)
- [x] Margins and links
- [x] Add a setting view ( https://github.com/slapperwan/gh4a/commit/e23d6cb5f5e8c04b244cabaaf2115772eb0479ed )
- [x] Minor: Branch selection & Holo icons for file explorer (#183)

---
### Comments Icon on Issue List
- As the GitHub behaviour and design, it should be cleaner to show a comment count only when there is one comment at least.
- Please use [Holo Stock icons](https://developer.android.com/design/downloads/index.html#action-bar-icon-pack), or another vector and less intrusive icon, to avoid "pixelation" and incoherence.

| Before | After |
| :-: | :-: |
| ![2014-04-24 17 35 39](https://cloud.githubusercontent.com/assets/846943/2794597/a024da8e-cbee-11e3-8277-e521226fcec6.png) | ![2014-04-24 17 35 39](https://cloud.githubusercontent.com/assets/846943/2794682/c98c7548-cbef-11e3-8002-292130157b6c.png) |

---
### Repository numbers
- Reorganization of the fourth numbers list may improve readability.
- Pull request should have a number.
- Maybe center align numbers.

| Before | After |
| :-: | :-: |
| ![2014-04-24 17 36 08](https://cloud.githubusercontent.com/assets/846943/2794741/9f62c028-cbf0-11e3-8102-cb8908387b4c.png) | ![2014-04-24 17 36 08](https://cloud.githubusercontent.com/assets/846943/2794904/cbb41c56-cbf2-11e3-9b9a-97d48615a6b7.png) |

---
### Theming (and improve) code view

Maybe when you will work on #101 :smile: 

| Before | After |
| :-: | :-: |
| ![2014-04-24 17 41 35](https://cloud.githubusercontent.com/assets/846943/2794958/78df2cfe-cbf3-11e3-9fda-65aaf43611d5.png) | ![2014-04-24 17 41 35](https://cloud.githubusercontent.com/assets/846943/2795112/87be960e-cbf5-11e3-9f96-79c6591ede68.png) |

---
### Margins and links

Some views have links shown in a good Holo list but doesn't respect margin and color conventions when hovering/clicking. 

| Before | After |
| :-: | :-: |
| ![2014-04-24 17 36 18](https://cloud.githubusercontent.com/assets/846943/2795253/cd8f7502-cbf7-11e3-8952-6b2cd20aea42.png) | ![2014-04-24 17 36 18](https://cloud.githubusercontent.com/assets/846943/2795286/376690c8-cbf8-11e3-972d-2f9773687627.png) |

---
### Settings Panel

In the following view, Theme, Logout and About should be placed in a specific config view as many other Android Holo Apllications.
This help to avoid users error, and to keep the interface clean.

| Actual | French but understandable Example |
| :-: | :-: |
| ![2014-04-16 22 55 54](https://cloud.githubusercontent.com/assets/846943/2795463/022c95ee-cbfb-11e3-891b-94ec854c1a4f.png) | ![2014-04-24 21 58 08](https://cloud.githubusercontent.com/assets/846943/2795502/adf4f45c-cbfb-11e3-929f-d86093f511d6.png) |

---
### Minor

| Branch selection | File explorer icons |
| --- | --- |
| Maybe more a bug than a design feature, but the current branch should be selected in the "switch branch" dialog. | Please use if possible [Holo Stock icons](https://developer.android.com/design/downloads/index.html#action-bar-icon-pack), or another vector and less intrusive icon, to avoid "pixelation" and incoherence. |
| ![2014-04-24 17 38 37](https://cloud.githubusercontent.com/assets/846943/2794950/6022eb42-cbf3-11e3-9d7d-5f6ea0d03a15.png) | ![2014-04-24 17 37 26](https://cloud.githubusercontent.com/assets/846943/2795203/e5498b02-cbf6-11e3-84a6-fbbdbfff2690.png) |
